# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/test.ipynb.

# %% auto 0
__all__ = ['calculation']

# %% ../nbs/test.ipynb 2
import pandas as pd
import numpy as np



# %% ../nbs/test.ipynb 3
def calculation(a,b):
    return a+b


